Make `hk run` show `run` help instead of crashing (#95)
`hk run` crashes. Probably is better to have it show the `hk run` help,
kinda like bare `hk` does.

Before:

```sh
 ❯ hk run

thread 'main' panicked at src/cli/run/mod.rs:34:28:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

After:

```sh
 ❯ hk run
Run a hook

Usage: run [OPTIONS] [FILES]... [COMMAND]

Commands:
  commit-msg          [aliases: cm]
  pre-commit          Sets up git hooks to run hk [aliases: pc]
  pre-push            [aliases: pp]
  prepare-commit-msg  [aliases: pcm]
  help                Print this message or the help of the given subcommand(s)

(etc)
```

Decided against adding a unit test because I didn't have a good feel for
the patterns you want to use there.